#!/bin/sh

if [ "$#" -ne 2 ]; then
    echo "Usage: subsume [path] [master.git]" 
    exit
fi

RELATIVE_PATH=$1
PARENT_URL=$2

mkdir -p $RELATIVE_PATH
git mv * $RELATIVE_PATH
git pull --strategy=recursive -Xours $PARENT_URL -m "Merge submodule $RELATIVE_PATH into $PARENT_URL."
